[package]
name = "detecting_pipeline_leaks_from_space_multi_sensor_satellite_monitoring_at_scale_with_databricks_rs"
description = "Python bindings (PyO3) for detecting_pipeline_leaks_from_space_multi_sensor_satellite_monitoring_at_scale_with_databricks_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "detecting_pipeline_leaks_from_space_multi_sensor_satellite_monitoring_at_scale_with_databricks_rs"
crate-type = ["cdylib"]

[dependencies]
detecting_pipeline_leaks_from_space_multi_sensor_satellite_monitoring_at_scale_with_databricks_core = { path = "../core" }
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
